### ISSUE TITLE
Cannot run the program

### ISSUE THREAD

**Issue by lokitkhemka** [kekeblom/mpm#1]
I built the program as given in the README and I keep getting the error:
```

./bin/mpm --scene ../scenes/snowman.toml
Loading scene file: ../scenes/snowman.toml
Warning: readOBJ() ignored non-comment line 1:
  version https://git-lfs.github.com/spec/v1
Warning: readOBJ() ignored non-comment line 2:
  oid sha256:24a15dfec58c5e82d2a33648a54860fc788730ef7fac8b0ed14262a5e7113ae0
Segmentation fault (core dumped)
```
Any help you can provide?

**Comment by kekeblom** [comment]
Did you pull the obj files with git lfs? Can you open the obj files with some other program?

**Comment by lokitkhemka** [comment]
Turns out I didn't. Let me do that.

**Comment by lokitkhemka** [comment]
Yeah. The problem was indeed that I didn't pull lfs objects. Thank you very much.
